# Generated by Django 5.0.1 on 2024-11-28 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meme",
            name="votes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="meme",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meme_creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="meme",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meme_round",
                to="api.round",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_round",
                to="api.room",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="meme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voted_meme",
                to="api.meme",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voter_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
