# Generated by Django 5.0.1 on 2024-11-28 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_meme_votes_alter_meme_creator_alter_meme_round_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meme",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="meme",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memes",
                to="api.round",
            ),
        ),
        migrations.RemoveField(
            model_name="meme",
            name="votes",
        ),
        migrations.AlterField(
            model_name="room",
            name="theme",
            field=models.CharField(
                blank=True,
                choices=[
                    ("memes", "Memes"),
                    ("animals", "Animals"),
                    ("movies", "Movies"),
                    ("sports", "Sports"),
                    ("music", "Music"),
                    ("technology", "Technology"),
                    ("food", "Food"),
                    ("nature", "Nature"),
                    ("gaming", "Gaming"),
                    ("art", "Art"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rounds",
                to="api.room",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="meme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes_received",
                to="api.meme",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes_cast",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meme",
            name="votes",
            field=models.ManyToManyField(
                blank=True, related_name="voted_memes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
