# Generated by Django 5.0.1 on 2024-11-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_meme_creator_alter_meme_round_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meme",
            name="image",
        ),
        migrations.AddField(
            model_name="meme",
            name="image_url",
            field=models.URLField(default=None),
        ),
    ]
