# Generated by Django 5.0.1 on 2024-11-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_meme_image_meme_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(
                default="Room <built-in function id>", max_length=255
            ),
        ),
    ]
